### ISSUE TITLE
Pubsub issue when max retry is reached

### ISSUE THREAD

**Issue by bip91** [zatosource/zato#989]
When max retry is reached (with notify), zato 3.1 raise the following error :

```
2019-09-20 12:54:46,191 - WARNING - 10195:DummyThread-8188 - zato:0 - Could not deliver pub/sub messages, e:`Traceback (most recent call last):
 File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pubsub/task.py", line 263, in run_delivery
if msg.delivery_count >= self.delivery_max_retry:
**TypeError: '>=' not supported between instances of 'int' and 'str'**
```

I add log to analyze issue that show it is the right value but the wrong type :
** 2019-09-20 12:54:46,190 - WARNING - 10195:DummyThread-8188 - zato:0 - [XXXX] message(s):`0`, <class 'str'>(`123456789`)**

it can be fixed by a cast delivery_max_retry to int :
```
#if msg.delivery_count >= self.delivery_max_retry:
if msg.delivery_count >= int(self.delivery_max_retry):
```
$ zato --version
Zato 3.1+rev.770617e-py3.6.8
$ git log
commit 770617e97a6b4b739bf08e66d800f85ed5656383 (HEAD -> support/3.1, origin/support/3.1)
...

**Comment by bip91** [comment]
This is not enough to stop zato retry to call the service forever.
When adding a logger in /zato-server/src/zato/server/pubsub/task.py line 263 : 

`for msg in current_batch:`
`     logger_zato.warn('[BPE-XXXX] message(s):`%s`, %s , %s(`%s`)',msg.delivery_count, self.delivery_counter, type(self.delivery_max_retry), self.delivery_max_retry)`
`      if msg.delivery_count >= int(self.delivery_max_retry):`

we can see that neither msg.delivery_count nor self.delivery_counter is incremented : 

`2019-10-14 21:49:39,310 - WARNING - 21211:DummyThread-13 - zato:0 - [BPE-XXXX] message(s):0, 0 , <class 'int'>(1)`
`2019-10-14 21:50:09,319 - WARNING - 21211:DummyThread-13 - zato:0 - [BPE-XXXX] message(s):0, 0 , <class 'int'>(1)`
`2019-10-14 21:50:39,326 - WARNING - 21211:DummyThread-13 - zato:0 - [BPE-XXXX] message(s):0, 0 , <class 'int'>(1)`

**self.delivery_counter seems not usefulbecause it is never incremented despite line 335 :** 
`self.delivery_counter += 1`

**But if we add in line 266 :**  
`msg.delivery_count += 1`

it works 👍 

`2019-10-14 21:53:02,607 - WARNING - 22455:DummyThread-13 - zato:0 - [BPE-XXXX] message(s):`0`, 0 , <class 'int'>(`1`)`
`2019-10-14 21:53:32,618 - WARNING - 22455:DummyThread-13 - zato:0 - [BPE-XXXX] message(s):`1`, 0 , <class 'int'>(`1`)`

**Comment by dsuch** [comment]
Thanks, yes, this is already corrected in one of the side branches that we be merged to main ones soon. I will let you know.

**Comment by dsuch** [comment]
This is done and pushed to GitHub, please git pull the updates and it will be included.

**Comment by bip91** [comment]
Hi dsuch,

Bug seems still present.

I get today a fully fresh docker with last Zato version.
$ zato --version
Zato 3.1+rev.5fbf78665-py3.6.8

Last commit  : 5fbf7866553a948fde022953f30e2bd818454497 (HEAD -> support/3.1, origin/support/3.1)

I build the following component : 
- topic : /test/pubsub
- endpoint : test
- subscription : notify to pubsub.demo.sample.outconn 

```
2019-11-07 22:01:23,428 - WARNING - 518:DummyThread-278 - zato:0 - Could not deliver pub/sub messages, e:`Traceback (most recent call last):
 File "/opt/zato/3.1.0/code/zato-server/src/zato/server/pubsub/task.py", line 270, in run_delivery
    if msg.delivery_count >= self.delivery_max_retry:
TypeError: '>=' not supported between instances of 'int' and 'str'
```
It works after applying the patch:

```
#if msg.delivery_count >= self.delivery_max_retry:
if msg.delivery_count >= int(self.delivery_max_retry):
```
