### ISSUE TITLE
IBM MQ installations problems

### ISSUE THREAD

**Issue by fenist19** [zatosource/zato#994]
In our environment we run zato and an IBM MQ server in separate docker containers, which are started with docker-compose.
We use the following  package versions:

1. zato version : Zato 3.1+rev.95b5cab9a-py3.6.8 in Ubuntu 18.04 in docker container
2. IBM MQ clients :  
-  9.1.0.2-IBM-MQC-UbuntuLinuxX64 (full install)
-  9.1.0.3-IBM-MQC-Redist-LinuxX64 
3. IBM MQ server in a docker container(https://github.com/ibm-messaging/mq-docker) ver.  9.1.2.0  and 9.1.3.0 
4. zato server option _ibm_mq=True_

I installed  an IBM MQ client in a zato-server container and pymqi==1.9.2.
After that I executed a python shell in the zato container and ran the following script.
```
import pymqi

queue_manager = 'QM1'
channel = 'DEV.ADMIN.SVRCONN'
host = '172.20.0.8'
port = '1414'
queue_name = 'DEV.QUEUE.1'
message = bytes('Hello from Python!', 'utf-8')
conn_info = '%s(%s)' % (host, port)

qmgr = pymqi.connect(queue_manager, channel, conn_info,user='admin', password='passw0rd')

queue = pymqi.Queue(qmgr, queue_name)
queue.put(message)
queue.close()

qmgr.disconnect()
```
The script successfully sent a message to the IBM MQ server.
The errors that were received in zato web admin and the actions that caused them are attached below:
1)
```
Could not ping IBM MQ definition, e:`Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 605, in id_only_service
    result = req.zato.client.invoke(service, request)
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 5c0224ee26a59f2e0f70dd96
Details: Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 677, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 498, in set_response_data
    response = response.getvalue(serialize=kwargs['serialize'])
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 470, in getvalue
    elem_value = self._getvalue(name, item, is_sa_namedtuple, is_required, leave_as_is)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/reqresp/__init__.py", line 418, in _getvalue
    raise ZatoException(self.zato_cid, msg)
zato.common.ZatoException: <ZatoException at 0x7f03420fc288 cid:`5c0224ee26a59f2e0f70dd96`, msg:`Expected elem:`info` not found in item:`{'info': ''}``>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 779, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 755, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 694, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/definition/jms_wmq.py", line 260, in handle
    self.server.connector_ibm_mq.ping_wmq(self.request.input.id)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/base/parallel/subprocess_/ibm_mq.py", line 61, in ping_wmq
    return self.ping(*args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 170, in ping
    'id': id
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 194, in invoke_connector
    address = address_pattern.format(self.ipc_tcp_port, 'api')
AttributeError: 'IBMMQIPC' object has no attribute 'ipc_tcp_port'

```
Error number 1 was received almost always 
on http://localhost:8183/zato/definition/jms-wmq/?cluster=1 after pressing the "ping" button.
Ping results were about as follows:
- 4 out of 5: error number 1
- 1 out of 5: with a message "\_Ping OK, took:\`0.010551\`\_ s" 

2) When we used "send message" on http://localhost:8183/zato/outgoing/jms-wmq/?cluster=1
we received the following error:
```
Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py", line 179, in send_message_action
    response = req.zato.client.invoke('zato.outgoing.jms-wmq.send-message', request)
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: fae7ec5f04fbed46c6204de6
Details: Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 779, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 755, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/outgoing/jms_wmq.py", line 230, in handle
    self.server.connector_ibm_mq.send_wmq_message(self.request.input)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/base/parallel/subprocess_/ibm_mq.py", line 57, in send_wmq_message
    out = self.send_message(*args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 180, in send_message
    response = self.invoke_connector(msg)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 199, in invoke_connector
    raise Exception(response.text)
Exception: Exception in _on_OUTGOING_WMQ_SEND (2) `Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/ibm_mq.py", line 297, in _on_OUTGOING_WMQ_SEND
    conn.send(text_msg, msg.queue_name.encode('utf8'))
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/jms_wmq/jms/connection.py", line 345, in send
    destination = self._strip_prefixes_from_destination(destination)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/jms_wmq/jms/connection.py", line 621, in _strip_prefixes_from_destination
    if destination.startswith('queue:///'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
`
```
or error 

```
Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py", line 179, in send_message_action
    response = req.zato.client.invoke('zato.outgoing.jms-wmq.send-message', request)
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 9c215c46b415700566e84245
Details: Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 779, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 755, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/outgoing/jms_wmq.py", line 230, in handle
    self.server.connector_ibm_mq.send_wmq_message(self.request.input)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/base/parallel/subprocess_/ibm_mq.py", line 57, in send_wmq_message
    out = self.send_message(*args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 180, in send_message
    response = self.invoke_connector(msg)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py", line 194, in invoke_connector
    address = address_pattern.format(self.ipc_tcp_port, 'api')
AttributeError: 'IBMMQIPC' object has no attribute 'ipc_tcp_port'
```

3) When we created a service with the source code:
```
class My(Service):

    def handle(self):
        self.outgoing.ibm_mq.send('my-message', 'test', 'DEV.QUEUE.1')
```
and invoke it, we received the following error:

```
Could not invoke the service. name:`my-services2.my`, cluster_id:`1`, e:`Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/web/views/service.py", line 555, in invoke
    response = req.zato.client.invoke(name, **input_dict)
  File "/opt/zato_dir/zato/code/zato-web-admin/src/zato/admin/middleware.py", line 82, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'), zato_env.get('details')))
Exception: CID: 10abca4cc4d079ac23cbb7b3
Details: Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/service.py", line 368, in handle
    response = func(id_, payload, channel, data_format, transport, serialize=True)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 779, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 755, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 699, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/env/server/work/hot-deploy/current/my_services2.py", line 8, in handle
    self.outgoing.ibm_mq.send('my-message', 'test', 'DEV.QUEUE.1')
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/jms_wmq/outgoing.py", line 31, in send
    return self.service.server.send_wmq_message({
AttributeError: 'ParallelServer' object has no attribute 'send_wmq_message'
```
There was not a single message to be sent the server successfully.

**Comment by dsuch** [comment]
Hello,

I pushed a few changes related to this ticket. Can you try it out now?

**Comment by fenist19** [comment]
I rebuilt zato with last changes.
The problem 1 is not solved.

The problem 2 with error  "AttributeError: 'IBMMQIPC' object has no attribute 'ipc_tcp_port'"   is not solved. 
Problem with error `TypeError: startswith first arg must be bytes or a tuple of bytes, not str` is solved. Sometimes we succesfully send message if we are not recived error with ports .

The problem 3 is not solved.

I found new error in IBM MQ channels:
http://localhost:8183/zato/channel/jms-wmq/?cluster=1
When I added message in query and zato recived it, we recived the following error:
```
2019-10-29 10:27:19,992 - WARNING - 136:DummyThread-46 - zato.server.service:0 - Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/channel/jms_wmq.py", line 247, in handle
    'mqmd': pickle_loads(msg['mqmd'].encode('utf8'))
AttributeError: 'bytes' object has no attribute 'encode'

2019-10-29 10:27:19,993 - WARNING - 136:DummyThread-46 - zato.server.service:0 - Exception in service `zato.channel.jms-wmq.on-message-received`, e:`Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 677, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 488, in _set_response_data
    self.set_payload(service.response, data_format, transport, service)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 681, in set_payload
    response.payload = self._get_xml_admin_payload(service_instance, zato_message_template, None)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 647, in _get_xml_admin_payload
    """.format(response_elem=getattr(service_instance.SimpleIO, 'response_elem', 'response'),
AttributeError: 'bytes' object has no attribute 'format'
`
2019-10-29 10:27:19,993 - ERROR - 136:DummyThread-46 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`4710f5d171a3108ed2b6f8c5`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 677, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 488, in _set_response_data
    self.set_payload(service.response, data_format, transport, service)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 681, in set_payload
    response.payload = self._get_xml_admin_payload(service_instance, zato_message_template, None)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 647, in _get_xml_admin_payload
    """.format(response_elem=getattr(service_instance.SimpleIO, 'response_elem', 'response'),
AttributeError: 'bytes' object has no attribute 'format'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 694, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 647, in update_handle
    self._invoke(service, channel)
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/__init__.py", line 534, in _invoke
    service.handle()
  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/service/internal/channel/jms_wmq.py", line 247, in handle
    'mqmd': pickle_loads(msg['mqmd'].encode('utf8'))
AttributeError: 'bytes' object has no attribute 'encode'

```
`

**Comment by fenist19** [comment]
Dear @dsuch,  Do you have plan to fix IbmMq problems? Do you have roadmap?

**Comment by dsuch** [comment]
Hello @fenist19,

our roadmap is based mostly on the needs of our commercial clients. Otherwise, with public GitHub tickets, we work on them when we are able to and there is no fixed schedule.

If you would like for this ticket or any other to be resolved under a commercial priority support contract, please feel free to contact me on dsuch@zato.io.

Regards.

**Comment by fenist19** [comment]
Can you help with you custom gunicorn? 
we fix all IBM MQ prolmes. after fix https://github.com/zatosource/zato/pull/1002 messages already send with one worker. But if we use 2+ workers - not main workers have problem with port - `'IBMMQIPC' object has no attribute 'ipc_tcp_port'.` can you help with this bug?

**Comment by dsuch** [comment]
Hello @fenist19 - yes, I will be looking into it as soon as I can. At this point, I cannot commit to any deadline.

**Comment by dsuch** [comment]
Also @fenist19 - I am closing this ticket because the original question is resolved.

If you want to open a new one, please provide the context. What you invoke, how you invoke it and what the full traceback is.
